using System;
using System.Collections.Generic;
using System.Text;
using Horizen.FullNode.API.Net.Standard.RPC;
using Horizen.FullNode.API.Net.Standard.RPCInputTypes;
using Horizen.FullNode.API.Net.Standard.RPCReturnTypes;
using Newtonsoft.Json;

namespace Horizen.FullNode.API.Net.Standard
{
    public partial class ZendRPC:IZendRPC
    {
        

        public T GetRPCTypedResult<T>(string method, object[] _params)
        {
            var result = new RPCConnection().RunCommand(method, _params);
            if (typeof(T) == typeof(string)
                || typeof(T) == typeof(int)
                || typeof(T) == typeof(long)
                || typeof(T) == typeof(float)
                || typeof(T) == typeof(double)
                || typeof(T) == typeof(bool))
            {
                return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(result.Replace("\"", "")));
            }
            else
            {
                return JsonConvert.DeserializeObject<T>(result);
            }
        }

        public static Dictionary<ZendRPCCommand, string> ZendRPCCommands = new Dictionary<ZendRPCCommand, string>
        {
            {ZendRPCCommand.GetBestBlockHash, "getbestblockhash"},
            {ZendRPCCommand.GetBlock, "getblock"},
            {ZendRPCCommand.GetBlockchainInfo, "getblockchaininfo"},
            {ZendRPCCommand.GetBlockCount, "getblockcount"},
            {ZendRPCCommand.GetBlockHash, "getblockhash"},
            {ZendRPCCommand.GetBlockHeader, "getblockheader"},
            {ZendRPCCommand.GetChainTips, "getchaintips"},
            {ZendRPCCommand.GetDifficulty, "getdifficulty"},
            {ZendRPCCommand.GetMemPoolInfo, "getmempoolinfo"},
            {ZendRPCCommand.GetRawMemPool, "getrawmempool"},
            {ZendRPCCommand.GetTxOut, "gettxout"},
            {ZendRPCCommand.GetTxOutProof, "gettxoutproof"},
            {ZendRPCCommand.GetTxOutSetInfo, "gettxoutsetinfo"},
            {ZendRPCCommand.VerifyChain, "verifychain"},
            {ZendRPCCommand.VerifyTxOutProof, "verifytxoutproof"},
            {ZendRPCCommand.GetInfo, "getinfo"},
            {ZendRPCCommand.Help, "help"},
            {ZendRPCCommand.Stop, "stop"},
            {ZendRPCCommand.ZGetPaymentDisclosure, "z_getpaymentdisclosure"},
            {ZendRPCCommand.ZValidatePaymentDisclosure, "z_validatepaymentdisclosure"},
            {ZendRPCCommand.Generate, "generate"},
            {ZendRPCCommand.GetGenerate, "getgenerate"},
            {ZendRPCCommand.SetGenerate, "setgenerate"},
            {ZendRPCCommand.GetBlockSubsidy, "getblocksubsidy"},
            {ZendRPCCommand.GetBlockTemplate, "getblocktemplate"},
            {ZendRPCCommand.GetLocalSolPs, "getlocalsolps"},
            {ZendRPCCommand.GetMiningInfo, "getmininginfo"},
            {ZendRPCCommand.GetNetworkHashPs, "getnetworkhashps"},
            {ZendRPCCommand.GetNetworkSolPs, "getnetworksolps"},
            {ZendRPCCommand.PrioritiseTransaction, "prioritisetransaction"},
            {ZendRPCCommand.SubmitBlock, "submitblock"},
            {ZendRPCCommand.AddNode, "addnode"},
            {ZendRPCCommand.ClearBanned, "clearbanned"},
            {ZendRPCCommand.DisconnectNode, "disconnectnode"},
            {ZendRPCCommand.GetAddedNodeInfo, "getaddednodeinfo"},
            {ZendRPCCommand.GetConnectionCount, "getconnectioncount"},
            {ZendRPCCommand.GetNetTotals, "getnettotals"},
            {ZendRPCCommand.GetNetworkInfo, "getnetworkinfo"},
            {ZendRPCCommand.GetPeerInfo, "getpeerinfo"},
            {ZendRPCCommand.ListBanned, "listbanned"},
            {ZendRPCCommand.Ping, "ping"},
            {ZendRPCCommand.SetBan, "setban"},
            {ZendRPCCommand.CreateRawTransaction, "createrawtransaction"},
            {ZendRPCCommand.DecodeRawTransaction, "decoderawtransaction"},
            {ZendRPCCommand.DecodeScript, "decodescript"},
            {ZendRPCCommand.FundRawTransaction, "fundrawtransaction"},
            {ZendRPCCommand.GetRawTransaction, "getrawtransaction"},
            {ZendRPCCommand.SendRawTransaction, "sendrawtransaction"},
            {ZendRPCCommand.SignRawTransaction, "signrawtransaction"},
            {ZendRPCCommand.CreateMultisig, "createmultisig"},
            {ZendRPCCommand.EstimateFee, "estimatefee"},
            {ZendRPCCommand.EstimatePriority, "estimatepriority"},
            {ZendRPCCommand.ValidateAddress, "validateaddress"},
            {ZendRPCCommand.VerifyMessage, "verifymessage"},
            {ZendRPCCommand.ZValidateAddress, "z_validateaddress"},
            {ZendRPCCommand.AddMultisigAddress, "addmultisigaddress"},
            {ZendRPCCommand.BackupWallet, "backupwallet"},
            {ZendRPCCommand.DumpPrivkey, "dumpprivkey"},
            {ZendRPCCommand.DumpWallet, "dumpwallet"},
            {ZendRPCCommand.EncryptWallet, "encryptwallet"},
            {ZendRPCCommand.GetAccount, "getaccount"},
            {ZendRPCCommand.GetAccountAddress, "getaccountaddress"},
            {ZendRPCCommand.GetAddressByAccount, "getaddressesbyaccount"},
            {ZendRPCCommand.GetBalance, "getbalance"},
            {ZendRPCCommand.GetNewAddress, "getnewaddress"},
            {ZendRPCCommand.GetRawChangeAddress, "getrawchangeaddress"},
            {ZendRPCCommand.GetReceivedByAccount, "getreceivedbyaccount"},
            {ZendRPCCommand.GetReceivedByAddress, "getreceivedbyaddress"},
            {ZendRPCCommand.GetTransaction, "gettransaction"},
            {ZendRPCCommand.GetUnconfirmedBalance, "getunconfirmedbalance"},
            {ZendRPCCommand.GetWalletInfo, "getwalletinfo"},
            {ZendRPCCommand.ImportAddress, "importaddress"},
            {ZendRPCCommand.ImportPrivkey, "importprivkey"},
            {ZendRPCCommand.ImportWallet, "importwallet"},
            {ZendRPCCommand.KeyPoolRefill, "keypoolrefill"},
            {ZendRPCCommand.ListAccounts, "listaccounts"},
            {ZendRPCCommand.ListAddresses, "listaddresses"},
            {ZendRPCCommand.ListAddressGroupings, "listaddressgroupings"},
            {ZendRPCCommand.ListLockUnspent, "listlockunspent"},
            {ZendRPCCommand.ListReceivedByAccount, "listreceivedbyaccount"},
            {ZendRPCCommand.ListReceivedByAddress, "listreceivedbyaddress"},
            {ZendRPCCommand.ListSinceBlock, "listsinceblock"},
            {ZendRPCCommand.ListTransactions, "listtransactions"},
            {ZendRPCCommand.ListUnspent, "listunspent"},
            {ZendRPCCommand.LockUnspent, "lockunspent"},
            {ZendRPCCommand.Move, "move"},
            {ZendRPCCommand.SendFrom, "sendfrom"},
            {ZendRPCCommand.SendMany, "sendmany"},
            {ZendRPCCommand.SendToAddress, "sendtoaddress"},
            {ZendRPCCommand.SetAccount, "setaccount"},
            {ZendRPCCommand.SetTxFee, "settxfee"},
            {ZendRPCCommand.SignMessage, "signmessage"},
            {ZendRPCCommand.ZExportKey, "z_exportkey"},
            {ZendRPCCommand.ZExportViewingKey, "z_exportviewingkey"},
            {ZendRPCCommand.ZExportWallet, "z_exportwallet"},
            {ZendRPCCommand.ZGetBalance, "z_getbalance"},
            {ZendRPCCommand.ZGetNewAddress, "z_getnewaddress"},
            {ZendRPCCommand.ZGetOperationResult, "z_getoperationresult"},
            {ZendRPCCommand.ZGetOperationStatus, "z_getoperationstatus"},
            {ZendRPCCommand.ZGetTotalBalance, "z_gettotalbalance"},
            {ZendRPCCommand.ZImportKey, "z_importkey"},
            {ZendRPCCommand.ZImportViewingKey, "z_importviewingkey"},
            {ZendRPCCommand.ZImportWallet, "z_importwallet"},
            {ZendRPCCommand.ZListAddresses, "z_listaddresses"},
            {ZendRPCCommand.ZListOperationIds, "z_listoperationids"},
            {ZendRPCCommand.ZListReceivedByAddress, "z_listreceivedbyaddress"},
            {ZendRPCCommand.ZSendMany, "z_sendmany"},
            {ZendRPCCommand.ZShieldCoinbase, "z_shieldcoinbase"},
            {ZendRPCCommand.ZCBenchmark, "zcbenchmark"},
            {ZendRPCCommand.ZCRawJoinSplit, "zcrawjoinsplit"},
            {ZendRPCCommand.ZCRawKeyGen, "zcrawkeygen"},
            {ZendRPCCommand.ZCRawReceive, "zcrawreceive"},
            {ZendRPCCommand.ZCSampleJoinSplit, "zcsamplejoinsplit"}
        };

        public enum ZendRPCCommand
        {
            //Blockchain
            GetBestBlockHash,
            GetBlock,
            GetBlockchainInfo,
            GetBlockCount,
            GetBlockHash,
            GetBlockHeader,
            GetChainTips,
            GetDifficulty,
            GetMemPoolInfo,
            GetRawMemPool,
            GetTxOut,
            GetTxOutProof,
            GetTxOutSetInfo,
            VerifyChain,
            VerifyTxOutProof,
            //Control
            GetInfo,
            Help,
            Stop,
            //Disclosure
            ZGetPaymentDisclosure,
            ZValidatePaymentDisclosure,
            //Generating
            Generate,
            GetGenerate,
            SetGenerate,
            //Mining
            GetBlockSubsidy,
            GetBlockTemplate,
            GetLocalSolPs,
            GetMiningInfo,
            GetNetworkHashPs,
            GetNetworkSolPs,
            PrioritiseTransaction,
            SubmitBlock,
            //Network
            AddNode,
            ClearBanned,
            DisconnectNode,
            GetAddedNodeInfo,
            GetConnectionCount,
            GetNetTotals,
            GetNetworkInfo,
            GetPeerInfo,
            ListBanned,
            Ping,
            SetBan,
            //Raw Transactions
            CreateRawTransaction,
            DecodeRawTransaction,
            DecodeScript,
            FundRawTransaction,
            GetRawTransaction,
            SendRawTransaction,
            SignRawTransaction,
            //Util
            CreateMultisig,
            EstimateFee,
            EstimatePriority,
            ValidateAddress,
            VerifyMessage,
            ZValidateAddress,
            //Wallet
            AddMultisigAddress,
            BackupWallet,
            DumpPrivkey,
            DumpWallet,
            EncryptWallet,
            GetAccount,
            GetAccountAddress,
            GetAddressByAccount,
            GetBalance,
            GetNewAddress,
            GetRawChangeAddress,
            GetReceivedByAccount,
            GetReceivedByAddress,
            GetTransaction,
            GetUnconfirmedBalance,
            GetWalletInfo,
            ImportAddress,
            ImportPrivkey,
            ImportWallet,
            KeyPoolRefill,
            ListAccounts,
            ListAddresses,
            ListAddressGroupings,
            ListLockUnspent,
            ListReceivedByAccount,
            ListReceivedByAddress,
            ListSinceBlock,
            ListTransactions,
            ListUnspent,
            LockUnspent,
            Move,
            SendFrom,
            SendMany,
            SendToAddress,
            SetAccount,
            SetTxFee,
            SignMessage,
            //Z Commands
            ZExportKey,
            ZExportViewingKey,
            ZExportWallet,
            ZGetBalance,
            ZGetNewAddress,
            ZGetOperationResult,
            ZGetOperationStatus,
            ZGetTotalBalance,
            ZImportKey,
            ZImportViewingKey,
            ZImportWallet,
            ZListAddresses,
            ZListOperationIds,
            ZListReceivedByAddress,
            ZSendMany,
            ZShieldCoinbase,
            ZCBenchmark,
            ZCRawJoinSplit,
            ZCRawKeyGen,
            ZCRawReceive,
            ZCSampleJoinSplit
        }

    }
}
